version: 1
builder:
  configs:
    -
      documentation_targets:
        - ContainerAPIService
        - ContainerAPIClient
        - ContainerKit
        - ContainerKitServices
        - ContainerRuntimeClient
        - ContainerRuntimeLinuxClient
        - ContainerRuntimeLinuxServer
        - ContainerNetworkClient
        - ContainerNetworkServer
        - ContainerNetworkVmnetServer
        - ContainerImagesService
        - ContainerImagesServiceClient
        - ContainerResource
        - ContainerLog
        - ContainerPlugin
        - ContainerXPC
        - TerminalProgress
      swift_version: '6.2'
