//===----------------------------------------------------------------------===//
// Copyright © 2026 Apple Inc. and the container project authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

import Foundation

public enum KubeProxyPFRenderer {
    private static let maximumTableNameLength = 31

    public static func renderAnchor(
        ruleSet: KubeProxyRuleSet,
        anchorName: String = "com.apple.container.kube-proxy",
        localPodCIDR: String,
        masqueradePodTraffic: Bool = false,
        egressInterface: String? = nil
    ) throws -> String {
        var lines: [String] = [
            "# generated by container-kube-proxy-macos",
            "# anchor: \(anchorName)",
            "# generation: \(ruleSet.generation)",
            "# local PodCIDR: \(localPodCIDR)",
            "",
        ]

        for rule in ruleSet.rules {
            let tableName = tableName(for: rule)
            let addresses = rule.backends.map(\.ip).sorted().joined(separator: ", ")
            lines.append("table <\(tableName)> persist { \(addresses) }")
        }

        if !ruleSet.rules.isEmpty {
            lines.append("")
        }

        if masqueradePodTraffic {
            guard let egressInterface,
                egressInterface.range(of: #"^[A-Za-z0-9._-]+$"#, options: .regularExpression) != nil
            else {
                throw KubeProxyMacOSError.applyFailed(
                    "an egress interface is required when Pod source NAT is enabled"
                )
            }
            lines.append(
                "nat on \(egressInterface) inet from \(localPodCIDR) to any -> (\(egressInterface))"
            )
            lines.append("")
        }

        for rule in ruleSet.rules {
            let tableName = tableName(for: rule)
            let backendPort = rule.backends[0].port
            let roundRobin = rule.backends.count > 1 ? " round-robin" : ""
            lines.append(
                "rdr pass inet proto \(rule.protocolName.pfName) from any to \(rule.clusterIP) port \(rule.servicePort) -> <\(tableName)> port \(backendPort)\(roundRobin)"
            )
        }

        if !ruleSet.issues.isEmpty {
            lines.append("")
            for issue in ruleSet.issues {
                lines.append("# issue \(issue.id): \(issue.message)")
            }
        }

        lines.append("")
        return lines.joined(separator: "\n")
    }

    public static func tableName(for rule: KubeProxyServiceRule) -> String {
        let raw = [
            "ckp",
            rule.namespace,
            rule.serviceName,
            rule.portName ?? "\(rule.servicePort)",
            rule.protocolName.rawValue.lowercased(),
            "\(rule.servicePort)",
        ].joined(separator: "_")

        let sanitized = raw.map { character -> Character in
            character.isLetter || character.isNumber ? character : "_"
        }
        let name = String(sanitized)
        guard name.utf8.count > maximumTableNameLength else {
            return name
        }

        let digest = fnv1a64(name.utf8)
        let suffix = String(format: "%010llx", digest & 0xff_ffff_ffff)
        let prefixLength = maximumTableNameLength - suffix.count - 1
        return "\(String(name.prefix(prefixLength)))_\(suffix)"
    }

    private static func fnv1a64(_ bytes: String.UTF8View) -> UInt64 {
        var hash: UInt64 = 0xcbf2_9ce4_8422_2325
        for byte in bytes {
            hash ^= UInt64(byte)
            hash &*= 0x100_0000_01b3
        }
        return hash
    }
}

public protocol KubeProxyRuleApplying: Sendable {
    func apply(
        _ ruleSet: KubeProxyRuleSet,
        localPodCIDR: String,
        masqueradePodTraffic: Bool
    ) throws
}

public struct KubeProxyPFRuleApplier: KubeProxyRuleApplying {
    public let config: KubeProxyPFConfig
    private let egressInterfaceResolver: any KubeProxyEgressInterfaceResolving

    public init(
        config: KubeProxyPFConfig = KubeProxyPFConfig(),
        egressInterfaceResolver: any KubeProxyEgressInterfaceResolving = KubeProxyDefaultIPv4EgressInterfaceResolver()
    ) {
        self.config = config
        self.egressInterfaceResolver = egressInterfaceResolver
    }

    public func apply(
        _ ruleSet: KubeProxyRuleSet,
        localPodCIDR: String,
        masqueradePodTraffic: Bool = false
    ) throws {
        guard let canonicalPodCIDR = KubeProxyIPv4CIDR.canonicalize(localPodCIDR),
            canonicalPodCIDR == localPodCIDR
        else {
            throw KubeProxyMacOSError.applyFailed("local PodCIDR is not canonical IPv4 CIDR")
        }
        let egressInterface = try resolvedEgressInterface(masqueradePodTraffic: masqueradePodTraffic)
        let fileManager = FileManager.default
        let configURL = URL(fileURLWithPath: config.configPath)
        let anchorsURL = URL(fileURLWithPath: config.anchorsPath)
        let anchorURL = anchorsURL.appendingPathComponent(config.anchorName)

        try ensurePFEnabled()
        try fileManager.createDirectory(at: anchorsURL, withIntermediateDirectories: true)

        let originalConfigData = fileManager.contents(atPath: configURL.path)
        let originalConfig =
            try originalConfigData.map { data in
                guard let value = String(data: data, encoding: .utf8) else {
                    throw KubeProxyMacOSError.applyFailed("\(config.configPath) is not valid UTF-8")
                }
                return value
            } ?? ""
        let originalAnchorData = fileManager.contents(atPath: anchorURL.path)
        let anchor = try KubeProxyPFRenderer.renderAnchor(
            ruleSet: ruleSet,
            anchorName: config.anchorName,
            localPodCIDR: canonicalPodCIDR,
            masqueradePodTraffic: masqueradePodTraffic,
            egressInterface: egressInterface
        )
        let candidateConfig = pfConfigWithAnchorReferences(
            content: originalConfig,
            anchorURL: anchorURL,
            includeNATAnchor: masqueradePodTraffic
        )
        let rootConfigChanged = candidateConfig != originalConfig
        var attemptedRootReload = false
        var attemptedAnchorReload = false

        do {
            try anchor.write(to: anchorURL, atomically: true, encoding: .utf8)
            if rootConfigChanged {
                try validateAndInstallConfig(candidateConfig, configURL: configURL)
                attemptedRootReload = true
                try runPFCTL(arguments: ["-f", configURL.path], failureMessage: "pfctl reload failed")
            } else {
                try runPFCTL(
                    arguments: ["-n", "-a", config.anchorName, "-f", anchorURL.path],
                    failureMessage: "pfctl anchor validation failed"
                )
                attemptedAnchorReload = true
                try runPFCTL(
                    arguments: ["-a", config.anchorName, "-f", anchorURL.path],
                    failureMessage: "pfctl anchor reload failed"
                )
            }
        } catch {
            let restoredAnchor = restoreFile(at: anchorURL, originalData: originalAnchorData)
            let restoredConfig = restoreFile(at: configURL, originalData: originalConfigData)
            if attemptedRootReload, restoredAnchor, restoredConfig, originalConfigData != nil {
                try? runPFCTL(arguments: ["-f", configURL.path], failureMessage: "pfctl rollback failed")
            } else if attemptedAnchorReload, restoredAnchor, originalAnchorData != nil {
                try? runPFCTL(
                    arguments: ["-a", config.anchorName, "-f", anchorURL.path],
                    failureMessage: "pfctl anchor rollback failed"
                )
            }
            throw error
        }
    }

    private func resolvedEgressInterface(masqueradePodTraffic: Bool) throws -> String {
        if let configured = config.configuredEgressInterface {
            return configured
        }
        guard masqueradePodTraffic else {
            // The renderer does not emit an interface-specific rule when NAT is disabled.
            return "lo0"
        }
        return try egressInterfaceResolver.resolveDefaultIPv4EgressInterface()
    }

    private func ensurePFEnabled() throws {
        let output = try runPFCTLReturningStdout(arguments: ["-s", "info"], failureMessage: "pfctl status check failed")
        guard
            output
                .split(separator: "\n")
                .contains(where: { line in
                    line.trimmingCharacters(in: .whitespaces).hasPrefix("Status: Enabled")
                })
        else {
            throw KubeProxyMacOSError.applyFailed("PF is not enabled; enable PF before starting container-kube-proxy-macos")
        }
    }

    private func pfConfigWithAnchorReferences(
        content: String,
        anchorURL: URL,
        includeNATAnchor: Bool
    ) -> String {
        let natAnchor = "nat-anchor \"\(config.anchorName)\""
        let rdrAnchor = "rdr-anchor \"\(config.anchorName)\""
        let loadAnchor = "load anchor \"\(config.anchorName)\" from \"\(anchorURL.path)\""
        var lines = content.components(separatedBy: .newlines)
        if lines.isEmpty {
            lines = [""]
        }

        let hasNATAnchor = lines.contains { line in
            line.trimmingCharacters(in: .whitespaces) == natAnchor
        }
        if includeNATAnchor, !hasNATAnchor {
            let insertionIndex =
                lines.firstIndex { line in
                    pfDirective(line, startsWith: "rdr-anchor") || pfDirective(line, startsWith: "nat-anchor")
                } ?? max(lines.endIndex - 1, lines.startIndex)
            lines.insert(natAnchor, at: insertionIndex)
        } else if !includeNATAnchor {
            lines.removeAll { line in
                line.trimmingCharacters(in: .whitespaces) == natAnchor
            }
        }

        if !lines.contains(where: { normalizedPFDirective($0) == rdrAnchor }) {
            let anchorKeywords = ["scrub-anchor", "nat-anchor", "rdr-anchor", "dummynet-anchor", "anchor", "load anchor"]
            let insertionIndex =
                lines.firstIndex { line in
                    anchorKeywords.drop(while: { $0 != "rdr-anchor" }).contains { keyword in
                        pfDirective(line, startsWith: keyword)
                    }
                } ?? max(lines.endIndex - 1, lines.startIndex)
            lines.insert(rdrAnchor, at: insertionIndex)
        }

        if !lines.contains(where: { normalizedPFDirective($0) == loadAnchor }) {
            lines.insert(loadAnchor, at: max(lines.endIndex - 1, lines.startIndex))
        }

        return lines.joined(separator: "\n")
    }

    private func validateAndInstallConfig(_ content: String, configURL: URL) throws {
        let temporaryURL =
            configURL
            .deletingLastPathComponent()
            .appendingPathComponent(".\(configURL.lastPathComponent).container-kube-proxy.\(UUID().uuidString).tmp")
        try content.write(to: temporaryURL, atomically: true, encoding: .utf8)
        defer {
            try? FileManager.default.removeItem(at: temporaryURL)
        }

        try runPFCTL(arguments: ["-n", "-f", temporaryURL.path], failureMessage: "pfctl validation failed")
        try content.write(to: configURL, atomically: true, encoding: .utf8)
    }

    private func normalizedPFDirective(_ line: String) -> String {
        line.trimmingCharacters(in: .whitespaces)
    }

    private func pfDirective(_ line: String, startsWith keyword: String) -> Bool {
        let directive = normalizedPFDirective(line)
        return directive.hasPrefix("\(keyword) ") || directive.hasPrefix("\(keyword)\t")
    }

    @discardableResult
    private func restoreFile(at url: URL, originalData: Data?) -> Bool {
        do {
            if let originalData {
                try originalData.write(to: url, options: .atomic)
            } else if FileManager.default.fileExists(atPath: url.path) {
                try FileManager.default.removeItem(at: url)
            }
            return true
        } catch {
            return false
        }
    }

    private func runPFCTL(arguments: [String], failureMessage: String) throws {
        let process = Process()
        let stderr = Pipe()
        process.executableURL = URL(fileURLWithPath: config.pfctlPath)
        process.arguments = arguments
        process.standardOutput = FileHandle.nullDevice
        process.standardError = stderr

        do {
            try process.run()
        } catch {
            throw KubeProxyMacOSError.applyFailed("\(failureMessage): \(error)")
        }

        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            let data = stderr.fileHandleForReading.readDataToEndOfFile()
            let output = String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            throw KubeProxyMacOSError.applyFailed("\(failureMessage) with status \(process.terminationStatus): \(output)")
        }
    }

    private func runPFCTLReturningStdout(arguments: [String], failureMessage: String) throws -> String {
        let process = Process()
        let stdout = Pipe()
        let stderr = Pipe()
        process.executableURL = URL(fileURLWithPath: config.pfctlPath)
        process.arguments = arguments
        process.standardOutput = stdout
        process.standardError = stderr

        do {
            try process.run()
        } catch {
            throw KubeProxyMacOSError.applyFailed("\(failureMessage): \(error)")
        }

        process.waitUntilExit()
        let outputData = stdout.fileHandleForReading.readDataToEndOfFile()
        guard process.terminationStatus == 0 else {
            let errorData = stderr.fileHandleForReading.readDataToEndOfFile()
            let output = String(data: errorData, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            throw KubeProxyMacOSError.applyFailed("\(failureMessage) with status \(process.terminationStatus): \(output)")
        }
        return String(data: outputData, encoding: .utf8) ?? ""
    }
}

public struct KubeProxyDryRunRuleApplier: KubeProxyRuleApplying {
    public let output: @Sendable (String) -> Void
    public let anchorName: String
    public let egressInterface: String?
    private let egressInterfaceResolver: any KubeProxyEgressInterfaceResolving

    public init(
        anchorName: String = "com.apple.container.kube-proxy",
        egressInterface: String? = nil,
        egressInterfaceResolver: any KubeProxyEgressInterfaceResolving = KubeProxyDefaultIPv4EgressInterfaceResolver(),
        output: @escaping @Sendable (String) -> Void
    ) {
        self.anchorName = anchorName
        self.egressInterface = egressInterface
        self.egressInterfaceResolver = egressInterfaceResolver
        self.output = output
    }

    public func apply(
        _ ruleSet: KubeProxyRuleSet,
        localPodCIDR: String,
        masqueradePodTraffic: Bool = false
    ) throws {
        guard let canonicalPodCIDR = KubeProxyIPv4CIDR.canonicalize(localPodCIDR),
            canonicalPodCIDR == localPodCIDR
        else {
            throw KubeProxyMacOSError.applyFailed("local PodCIDR is not canonical IPv4 CIDR")
        }
        let resolvedEgressInterface: String
        if let egressInterface {
            resolvedEgressInterface = egressInterface
        } else if masqueradePodTraffic {
            resolvedEgressInterface = try egressInterfaceResolver.resolveDefaultIPv4EgressInterface()
        } else {
            resolvedEgressInterface = "lo0"
        }
        output(
            try KubeProxyPFRenderer.renderAnchor(
                ruleSet: ruleSet,
                anchorName: anchorName,
                localPodCIDR: canonicalPodCIDR,
                masqueradePodTraffic: masqueradePodTraffic,
                egressInterface: resolvedEgressInterface
            ))
    }
}
