//===----------------------------------------------------------------------===//
// Copyright © 2026 Apple Inc. and the container project authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

import Darwin
import Foundation

public enum KubeProxyPFCoordination {
    public static let advisoryLockPath = "/var/run/com.apple.container.pf.lock"
}

public enum KubeProxyPFRenderer {
    private static let maximumTableNameLength = 31
    private static let hairpinTag = "ckp_hairpin"

    public static func renderAnchor(
        ruleSet: KubeProxyRuleSet,
        anchorName: String = "com.apple.container.kube-proxy",
        localPodCIDR: String,
        podIngressInterface: String,
        masqueradePodTraffic: Bool = false,
        egressInterface: String? = nil,
        egressSourceAddress: String? = nil
    ) throws -> String {
        guard
            podIngressInterface.range(
                of: #"^[A-Za-z0-9._-]+$"#,
                options: .regularExpression
            ) != nil
        else {
            throw KubeProxyMacOSError.applyFailed("a valid Pod ingress interface is required")
        }
        let podFamily: KubeProxyAddressFamily
        if KubeProxyIPv4CIDR.canonicalize(localPodCIDR) == localPodCIDR {
            podFamily = .ipv4
        } else if KubeProxyIPv6CIDR.canonicalize(localPodCIDR) == localPodCIDR {
            podFamily = .ipv6
        } else {
            throw KubeProxyMacOSError.applyFailed("local PodCIDR is not canonical")
        }
        guard ruleSet.rules.allSatisfy({ $0.family == podFamily }) else {
            throw KubeProxyMacOSError.applyFailed(
                "PF anchor rules and local PodCIDR must use one address family"
            )
        }
        let hasHairpinNAT = requiresHairpinNAT(
            ruleSet: ruleSet,
            localPodCIDR: localPodCIDR
        )
        let hairpinGateway =
            try hasHairpinNAT
            ? gatewayAddress(family: podFamily, localPodCIDR: localPodCIDR)
            : nil
        var lines: [String] = [
            "# generated by container-kube-proxy-macos",
            "# anchor: \(anchorName)",
            "# generation: \(ruleSet.generation)",
            "# local PodCIDR: \(localPodCIDR)",
            "# Pod ingress interface: \(podIngressInterface)",
            "",
        ]

        for rule in ruleSet.rules {
            let tableName = tableName(for: rule)
            let addresses = rule.backends.map(\.ip).sorted().joined(separator: ", ")
            lines.append("table <\(tableName)> persist { \(addresses) }")
            let localBackendAddresses = localBackends(for: rule, localPodCIDR: localPodCIDR)
                .map(\.ip)
                .sorted()
            if !localBackendAddresses.isEmpty {
                lines.append(
                    "table <\(hairpinTableName(for: rule))> persist { \(localBackendAddresses.joined(separator: ", ")) }"
                )
            }
        }

        if !ruleSet.rules.isEmpty {
            lines.append("")
        }

        if masqueradePodTraffic {
            guard let egressInterface,
                egressInterface.range(of: #"^[A-Za-z0-9._-]+$"#, options: .regularExpression) != nil
            else {
                throw KubeProxyMacOSError.applyFailed(
                    "an egress interface is required when Pod source NAT is enabled"
                )
            }
            switch podFamily {
            case .ipv4:
                lines.append(
                    "nat on \(egressInterface) inet from \(localPodCIDR) to any -> (\(egressInterface))"
                )
            case .ipv6:
                guard let egressSourceAddress,
                    KubeProxyIPv6CIDR.canonicalize("\(egressSourceAddress)/128")
                        == "\(egressSourceAddress)/128"
                else {
                    throw KubeProxyMacOSError.applyFailed(
                        "a canonical IPv6 egress source address is required when IPv6 Pod source NAT is enabled"
                    )
                }
                lines.append(
                    "nat on \(egressInterface) inet6 from \(localPodCIDR) to any -> \(egressSourceAddress)"
                )
            }
        }

        for rule in ruleSet.rules where !localBackends(for: rule, localPodCIDR: localPodCIDR).isEmpty {
            let backendPort = rule.backends[0].port
            guard let hairpinGateway else {
                throw KubeProxyMacOSError.applyFailed("hairpin gateway address is missing")
            }
            lines.append(
                "nat on \(podIngressInterface) \(rule.family.pfName) proto \(rule.protocolName.pfName) from \(localPodCIDR) to <\(hairpinTableName(for: rule))> port \(backendPort) tagged \(hairpinTag) -> \(hairpinGateway)"
            )
        }

        if masqueradePodTraffic || hasHairpinNAT {
            lines.append("")
        }

        for rule in ruleSet.rules where rule.backends[0].port != rule.servicePort {
            let tableName = tableName(for: rule)
            let backendPort = rule.backends[0].port
            lines.append(
                "no rdr on \(podIngressInterface) \(rule.family.pfName) proto \(rule.protocolName.pfName) from <\(tableName)> port \(backendPort) to \(localPodCIDR)"
            )
        }

        for rule in ruleSet.rules {
            let tableName = tableName(for: rule)
            let backendPort = rule.backends[0].port
            let roundRobin = rule.backends.count > 1 ? " round-robin" : ""
            // A no-op proxy port makes macOS PF reverse-match backend traffic
            // against the rdr rule before any state exists. Preserve the port
            // implicitly when the Service and backend ports are equal.
            let redirectedPort = backendPort == rule.servicePort ? "" : " port \(backendPort)"
            let hairpinTagOption =
                localBackends(for: rule, localPodCIDR: localPodCIDR).isEmpty
                ? "" : " tag \(hairpinTag)"
            lines.append(
                "rdr pass on \(podIngressInterface) \(rule.family.pfName) proto \(rule.protocolName.pfName) from \(localPodCIDR) to \(rule.clusterIP) port \(rule.servicePort)\(hairpinTagOption) -> <\(tableName)>\(redirectedPort)\(roundRobin)"
            )
        }

        if !ruleSet.issues.isEmpty {
            lines.append("")
            for issue in ruleSet.issues {
                lines.append("# issue \(issue.id): \(issue.message)")
            }
        }

        lines.append("")
        return lines.joined(separator: "\n")
    }

    public static func tableName(for rule: KubeProxyServiceRule) -> String {
        makeTableName(prefix: "ckp", rule: rule)
    }

    static func requiresHairpinNAT(
        ruleSet: KubeProxyRuleSet,
        localPodCIDR: String
    ) -> Bool {
        ruleSet.rules.contains { rule in
            !localBackends(for: rule, localPodCIDR: localPodCIDR).isEmpty
        }
    }

    private static func hairpinTableName(for rule: KubeProxyServiceRule) -> String {
        makeTableName(prefix: "ckh", rule: rule)
    }

    private static func makeTableName(
        prefix: String,
        rule: KubeProxyServiceRule
    ) -> String {
        let raw = [
            prefix,
            rule.family.tableNameComponent,
            rule.namespace,
            rule.serviceName,
            rule.portName ?? "\(rule.servicePort)",
            rule.protocolName.rawValue.lowercased(),
            "\(rule.servicePort)",
        ].joined(separator: "_")

        let sanitized = raw.map { character -> Character in
            character.isLetter || character.isNumber ? character : "_"
        }
        let name = String(sanitized)
        guard name.utf8.count > maximumTableNameLength else {
            return name
        }

        let digest = fnv1a64(name.utf8)
        let suffix = String(format: "%010llx", digest & 0xff_ffff_ffff)
        let prefixLength = maximumTableNameLength - suffix.count - 1
        return "\(String(name.prefix(prefixLength)))_\(suffix)"
    }

    private static func localBackends(
        for rule: KubeProxyServiceRule,
        localPodCIDR: String
    ) -> [KubeProxyBackend] {
        guard let prefixLength = localPodCIDR.split(separator: "/", maxSplits: 1).last else {
            return []
        }
        return rule.backends.filter { backend in
            let addressCIDR = "\(backend.ip)/\(prefixLength)"
            switch rule.family {
            case .ipv4:
                return KubeProxyIPv4CIDR.canonicalize(addressCIDR) == localPodCIDR
            case .ipv6:
                return KubeProxyIPv6CIDR.canonicalize(addressCIDR) == localPodCIDR
            }
        }
    }

    private static func gatewayAddress(
        family: KubeProxyAddressFamily,
        localPodCIDR: String
    ) throws -> String {
        let components = localPodCIDR.split(separator: "/", omittingEmptySubsequences: false)
        guard components.count == 2, let prefixLength = Int(components[1]) else {
            throw KubeProxyMacOSError.applyFailed("local PodCIDR could not be parsed")
        }

        switch family {
        case .ipv4:
            guard prefixLength <= 30 else {
                throw KubeProxyMacOSError.applyFailed(
                    "local IPv4 PodCIDR must contain a gateway address"
                )
            }
            var address = in_addr()
            guard String(components[0]).withCString({ inet_pton(AF_INET, $0, &address) }) == 1 else {
                throw KubeProxyMacOSError.applyFailed("local IPv4 PodCIDR address could not be parsed")
            }
            withUnsafeMutableBytes(of: &address) { bytes in
                bytes[bytes.count - 1] &+= 1
            }
            return try addressString(address)

        case .ipv6:
            guard prefixLength <= 126 else {
                throw KubeProxyMacOSError.applyFailed(
                    "local IPv6 PodCIDR must contain a gateway address"
                )
            }
            var address = in6_addr()
            guard String(components[0]).withCString({ inet_pton(AF_INET6, $0, &address) }) == 1 else {
                throw KubeProxyMacOSError.applyFailed("local IPv6 PodCIDR address could not be parsed")
            }
            withUnsafeMutableBytes(of: &address) { bytes in
                bytes[bytes.count - 1] &+= 1
            }
            return try addressString(address)
        }
    }

    private static func addressString(_ value: in_addr) throws -> String {
        var address = value
        var buffer = [CChar](repeating: 0, count: Int(INET_ADDRSTRLEN))
        guard inet_ntop(AF_INET, &address, &buffer, socklen_t(buffer.count)) != nil else {
            throw KubeProxyMacOSError.applyFailed("Pod network gateway address could not be formatted")
        }
        return decodedAddressBuffer(buffer)
    }

    private static func addressString(_ value: in6_addr) throws -> String {
        var address = value
        var buffer = [CChar](repeating: 0, count: Int(INET6_ADDRSTRLEN))
        guard inet_ntop(AF_INET6, &address, &buffer, socklen_t(buffer.count)) != nil else {
            throw KubeProxyMacOSError.applyFailed("Pod network gateway address could not be formatted")
        }
        return decodedAddressBuffer(buffer)
    }

    private static func decodedAddressBuffer(_ buffer: [CChar]) -> String {
        String(
            decoding: buffer.prefix { $0 != 0 }.map { UInt8(bitPattern: $0) },
            as: UTF8.self
        )
    }

    private static func fnv1a64(_ bytes: String.UTF8View) -> UInt64 {
        var hash: UInt64 = 0xcbf2_9ce4_8422_2325
        for byte in bytes {
            hash ^= UInt64(byte)
            hash &*= 0x100_0000_01b3
        }
        return hash
    }
}

public protocol KubeProxyRuleApplying: Sendable {
    func apply(
        _ ruleSet: KubeProxyRuleSet,
        localPodCIDR: String,
        masqueradePodTraffic: Bool
    ) throws

    func apply(
        _ ruleSet: KubeProxyRuleSet,
        podNetwork: KubeProxyFamilyRuleApplication
    ) throws

    func withdraw() throws

    func withdrawIPv6() throws
}

public struct KubeProxyFamilyRuleApplication: Sendable, Equatable {
    public var ipv4PodCIDR: String
    public var ipv6PodCIDR: String?
    public var ipv4Ready: Bool
    public var ipv6Ready: Bool
    public var dualStackEnabled: Bool
    public var masqueradeIPv4PodTraffic: Bool
    public var masqueradeIPv6PodTraffic: Bool

    public init(
        ipv4PodCIDR: String,
        ipv6PodCIDR: String? = nil,
        ipv4Ready: Bool = true,
        ipv6Ready: Bool = false,
        dualStackEnabled: Bool = false,
        masqueradeIPv4PodTraffic: Bool = true,
        masqueradeIPv6PodTraffic: Bool = true
    ) {
        self.ipv4PodCIDR = ipv4PodCIDR
        self.ipv6PodCIDR = ipv6PodCIDR
        self.ipv4Ready = ipv4Ready
        self.ipv6Ready = ipv6Ready
        self.dualStackEnabled = dualStackEnabled
        self.masqueradeIPv4PodTraffic = masqueradeIPv4PodTraffic
        self.masqueradeIPv6PodTraffic = masqueradeIPv6PodTraffic
    }
}

extension KubeProxyRuleApplying {
    public func apply(
        _ ruleSet: KubeProxyRuleSet,
        podNetwork: KubeProxyFamilyRuleApplication
    ) throws {
        guard podNetwork.ipv4Ready else {
            throw KubeProxyMacOSError.applyFailed("pod network IPv4 family is not ready")
        }
        guard !podNetwork.dualStackEnabled else {
            throw KubeProxyMacOSError.unsupported(
                "this rule applier does not implement dual-stack family transactions"
            )
        }
        try apply(
            ruleSet.selecting(families: [.ipv4]),
            localPodCIDR: podNetwork.ipv4PodCIDR,
            masqueradePodTraffic: podNetwork.masqueradeIPv4PodTraffic
        )
    }

    public func withdraw() throws {
        throw KubeProxyMacOSError.unsupported("this rule applier does not implement PF withdrawal")
    }

    public func withdrawIPv6() throws {
        throw KubeProxyMacOSError.unsupported("this rule applier does not implement IPv6 PF withdrawal")
    }
}

public struct KubeProxyPFRuleApplier: KubeProxyRuleApplying {
    public let config: KubeProxyPFConfig
    private let egressInterfaceResolver: any KubeProxyEgressInterfaceResolving
    private let ipv6EgressResolver: any KubeProxyIPv6EgressResolving
    private let podIngressInterfaceResolver: any KubeProxyPodIngressInterfaceResolving
    private let advisoryLockPath: String

    // NSLock covers callers in this process; the advisory lock coordinates
    // cooperating PF writers across processes. Direct pfctl calls remain outside it.
    private static let processApplyLock = NSLock()

    public init(
        config: KubeProxyPFConfig = KubeProxyPFConfig(),
        egressInterfaceResolver: any KubeProxyEgressInterfaceResolving = KubeProxyDefaultIPv4EgressInterfaceResolver(),
        ipv6EgressResolver: any KubeProxyIPv6EgressResolving = KubeProxyDefaultIPv6EgressResolver(),
        podIngressInterfaceResolver: any KubeProxyPodIngressInterfaceResolving = KubeProxyDefaultPodIngressInterfaceResolver()
    ) {
        self.init(
            config: config,
            egressInterfaceResolver: egressInterfaceResolver,
            ipv6EgressResolver: ipv6EgressResolver,
            podIngressInterfaceResolver: podIngressInterfaceResolver,
            advisoryLockPath: KubeProxyPFCoordination.advisoryLockPath
        )
    }

    init(
        config: KubeProxyPFConfig,
        egressInterfaceResolver: any KubeProxyEgressInterfaceResolving = KubeProxyDefaultIPv4EgressInterfaceResolver(),
        ipv6EgressResolver: any KubeProxyIPv6EgressResolving = KubeProxyDefaultIPv6EgressResolver(),
        podIngressInterfaceResolver: any KubeProxyPodIngressInterfaceResolving = KubeProxyDefaultPodIngressInterfaceResolver(),
        advisoryLockPath: String
    ) {
        self.config = config
        self.egressInterfaceResolver = egressInterfaceResolver
        self.ipv6EgressResolver = ipv6EgressResolver
        self.podIngressInterfaceResolver = podIngressInterfaceResolver
        self.advisoryLockPath = advisoryLockPath
    }

    public func apply(
        _ ruleSet: KubeProxyRuleSet,
        localPodCIDR: String,
        masqueradePodTraffic: Bool = false
    ) throws {
        try withMutationLock {
            try applyLegacyLocked(
                ruleSet.selecting(families: [.ipv4]),
                localPodCIDR: localPodCIDR,
                masqueradePodTraffic: masqueradePodTraffic
            )
        }
    }

    public func apply(
        _ ruleSet: KubeProxyRuleSet,
        podNetwork: KubeProxyFamilyRuleApplication
    ) throws {
        try withMutationLock {
            guard podNetwork.ipv4Ready else {
                throw KubeProxyMacOSError.applyFailed("pod network IPv4 family is not ready")
            }
            guard let canonicalIPv4PodCIDR = KubeProxyIPv4CIDR.canonicalize(podNetwork.ipv4PodCIDR),
                canonicalIPv4PodCIDR == podNetwork.ipv4PodCIDR
            else {
                throw KubeProxyMacOSError.applyFailed("local IPv4 PodCIDR is not canonical")
            }

            let canonicalIPv6PodCIDR: String?
            if podNetwork.dualStackEnabled, podNetwork.ipv6Ready {
                guard let ipv6PodCIDR = podNetwork.ipv6PodCIDR,
                    let canonical = KubeProxyIPv6CIDR.canonicalize(ipv6PodCIDR),
                    canonical == ipv6PodCIDR
                else {
                    throw KubeProxyMacOSError.applyFailed(
                        "ready IPv6 family requires a canonical local IPv6 PodCIDR"
                    )
                }
                canonicalIPv6PodCIDR = canonical
            } else {
                canonicalIPv6PodCIDR = nil
            }

            let originalConfig = try readPFConfig()
            let ipv6AnchorURL = anchorURL(named: config.ipv6AnchorName)
            let hasStaleIPv6State =
                FileManager.default.fileExists(atPath: ipv6AnchorURL.path)
                || hasAnchorReferences(content: originalConfig.content, anchorName: config.ipv6AnchorName)

            if !podNetwork.ipv6Ready, !hasStaleIPv6State {
                try applyLegacyLocked(
                    ruleSet.selecting(families: [.ipv4]),
                    localPodCIDR: canonicalIPv4PodCIDR,
                    masqueradePodTraffic: podNetwork.masqueradeIPv4PodTraffic
                )
                return
            }

            try applyFamiliesLocked(
                ruleSet,
                podNetwork: podNetwork,
                canonicalIPv4PodCIDR: canonicalIPv4PodCIDR,
                canonicalIPv6PodCIDR: canonicalIPv6PodCIDR,
                originalConfig: originalConfig
            )
        }
    }

    public func withdraw() throws {
        try withMutationLock {
            try withdrawLocked(families: [.ipv4, .ipv6])
        }
    }

    public func withdrawIPv6() throws {
        try withMutationLock {
            try withdrawLocked(families: [.ipv6])
        }
    }

    private func withdrawLocked(families: Set<KubeProxyAddressFamily>) throws {
        let fileManager = FileManager.default
        let configURL = URL(fileURLWithPath: config.configPath)
        let ipv4AnchorURL = anchorURL(named: config.anchorName)
        let ipv6AnchorURL = anchorURL(named: config.ipv6AnchorName)
        let originalConfig = try readPFConfig()
        guard originalConfig.data != nil else {
            throw KubeProxyMacOSError.applyFailed("PF config is missing at \(config.configPath)")
        }
        let originalIPv4AnchorData = fileManager.contents(atPath: ipv4AnchorURL.path)
        let originalIPv6AnchorData = fileManager.contents(atPath: ipv6AnchorURL.path)
        var candidateConfig = originalConfig.content
        if families.contains(.ipv4) {
            candidateConfig = try pfConfigWithAnchorReferences(
                content: candidateConfig,
                anchorName: config.anchorName,
                anchorURL: ipv4AnchorURL,
                includeNATAnchor: false,
                enabled: false
            )
        }
        if families.contains(.ipv6) {
            candidateConfig = try pfConfigWithAnchorReferences(
                content: candidateConfig,
                anchorName: config.ipv6AnchorName,
                anchorURL: ipv6AnchorURL,
                includeNATAnchor: false,
                enabled: false
            )
        }
        let hasManagedAnchorFiles =
            (families.contains(.ipv4) && originalIPv4AnchorData != nil)
            || (families.contains(.ipv6) && originalIPv6AnchorData != nil)
        if candidateConfig == originalConfig.content, !hasManagedAnchorFiles {
            try flushManagedAnchors(families)
            return
        }
        var attemptedRootReload = false

        do {
            try validateAndInstallConfig(candidateConfig, configURL: configURL)
            attemptedRootReload = true
            try runPFCTL(arguments: ["-f", configURL.path], failureMessage: "pfctl reload failed")
            try flushManagedAnchors(families)
            if families.contains(.ipv4) {
                try removeFileIfPresent(at: ipv4AnchorURL)
            }
            if families.contains(.ipv6) {
                try removeFileIfPresent(at: ipv6AnchorURL)
            }
        } catch {
            let restoredIPv4Anchor = restoreFile(at: ipv4AnchorURL, originalData: originalIPv4AnchorData)
            let restoredIPv6Anchor = restoreFile(at: ipv6AnchorURL, originalData: originalIPv6AnchorData)
            let restoredConfig = restoreFile(at: configURL, originalData: originalConfig.data)
            var rollbackFailures = fileRestoreFailures(
                restoredFiles: [
                    (restoredIPv4Anchor, ipv4AnchorURL),
                    (restoredIPv6Anchor, ipv6AnchorURL),
                    (restoredConfig, configURL),
                ]
            )
            if attemptedRootReload, restoredIPv4Anchor, restoredIPv6Anchor, restoredConfig {
                if let failure = rollbackFailure({
                    try runPFCTL(arguments: ["-f", configURL.path], failureMessage: "pfctl rollback failed")
                }) {
                    rollbackFailures.append(failure)
                }
            }
            throw errorIncludingRollbackFailures(error, rollbackFailures: rollbackFailures)
        }
    }

    private func applyLegacyLocked(
        _ ruleSet: KubeProxyRuleSet,
        localPodCIDR: String,
        masqueradePodTraffic: Bool
    ) throws {
        guard let canonicalPodCIDR = KubeProxyIPv4CIDR.canonicalize(localPodCIDR),
            canonicalPodCIDR == localPodCIDR
        else {
            throw KubeProxyMacOSError.applyFailed("local PodCIDR is not canonical IPv4 CIDR")
        }
        let egressInterface = try resolvedEgressInterface(masqueradePodTraffic: masqueradePodTraffic)
        let podIngressInterface = try resolvePodIngressInterface(
            family: .ipv4,
            podCIDR: canonicalPodCIDR,
            withdrawFamiliesOnFailure: [.ipv4]
        )
        let fileManager = FileManager.default
        let configURL = URL(fileURLWithPath: config.configPath)
        let anchorsURL = URL(fileURLWithPath: config.anchorsPath)
        let anchorURL = anchorURL(named: config.anchorName)

        try ensurePFEnabled()
        try fileManager.createDirectory(at: anchorsURL, withIntermediateDirectories: true)

        let originalConfigData = fileManager.contents(atPath: configURL.path)
        let originalConfig =
            try originalConfigData.map { data in
                guard let value = String(data: data, encoding: .utf8) else {
                    throw KubeProxyMacOSError.applyFailed("\(config.configPath) is not valid UTF-8")
                }
                return value
            } ?? ""
        let originalAnchorData = fileManager.contents(atPath: anchorURL.path)
        let anchor = try KubeProxyPFRenderer.renderAnchor(
            ruleSet: ruleSet,
            anchorName: config.anchorName,
            localPodCIDR: canonicalPodCIDR,
            podIngressInterface: podIngressInterface,
            masqueradePodTraffic: masqueradePodTraffic,
            egressInterface: egressInterface
        )
        let candidateConfig = try pfConfigWithAnchorReferences(
            content: originalConfig,
            anchorName: config.anchorName,
            anchorURL: anchorURL,
            includeNATAnchor: true,
            enabled: true
        )
        let rootConfigChanged = candidateConfig != originalConfig
        var attemptedRootReload = false
        var attemptedAnchorReload = false

        do {
            try anchor.write(to: anchorURL, atomically: true, encoding: .utf8)
            if rootConfigChanged {
                try validateAndInstallConfig(candidateConfig, configURL: configURL)
                attemptedRootReload = true
                try runPFCTL(arguments: ["-f", configURL.path], failureMessage: "pfctl reload failed")
            } else {
                try runPFCTL(
                    arguments: ["-n", "-a", config.anchorName, "-f", anchorURL.path],
                    failureMessage: "pfctl anchor validation failed"
                )
                attemptedAnchorReload = true
                try runPFCTL(
                    arguments: ["-a", config.anchorName, "-f", anchorURL.path],
                    failureMessage: "pfctl anchor reload failed"
                )
            }
        } catch {
            let restoredAnchor = restoreFile(at: anchorURL, originalData: originalAnchorData)
            let restoredConfig = restoreFile(at: configURL, originalData: originalConfigData)
            var rollbackFailures = fileRestoreFailures(
                restoredFiles: [
                    (restoredAnchor, anchorURL),
                    (restoredConfig, configURL),
                ]
            )
            if attemptedRootReload, restoredAnchor, restoredConfig, originalConfigData != nil {
                if let failure = rollbackFailure({
                    try runPFCTL(arguments: ["-f", configURL.path], failureMessage: "pfctl rollback failed")
                }) {
                    rollbackFailures.append(failure)
                }
            } else if attemptedAnchorReload, restoredAnchor {
                if originalAnchorData != nil {
                    if let failure = rollbackFailure({
                        try runPFCTL(
                            arguments: ["-a", config.anchorName, "-f", anchorURL.path],
                            failureMessage: "pfctl anchor rollback failed"
                        )
                    }) {
                        rollbackFailures.append(failure)
                    }
                } else if let failure = rollbackFailure({
                    try runPFCTL(
                        arguments: ["-a", config.anchorName, "-F", "all"],
                        failureMessage: "pfctl anchor rollback flush failed"
                    )
                }) {
                    rollbackFailures.append(failure)
                }
            }
            throw errorIncludingRollbackFailures(error, rollbackFailures: rollbackFailures)
        }
    }

    private func applyFamiliesLocked(
        _ ruleSet: KubeProxyRuleSet,
        podNetwork: KubeProxyFamilyRuleApplication,
        canonicalIPv4PodCIDR: String,
        canonicalIPv6PodCIDR: String?,
        originalConfig: (data: Data?, content: String)
    ) throws {
        let fileManager = FileManager.default
        let configURL = URL(fileURLWithPath: config.configPath)
        let anchorsURL = URL(fileURLWithPath: config.anchorsPath)
        let ipv4AnchorURL = anchorURL(named: config.anchorName)
        let ipv6AnchorURL = anchorURL(named: config.ipv6AnchorName)
        let ipv6Active = podNetwork.dualStackEnabled && podNetwork.ipv6Ready
        let egressInterface = try resolvedEgressInterface(
            masqueradePodTraffic: podNetwork.masqueradeIPv4PodTraffic
        )
        let ipv6Egress = try resolvedIPv6Egress(
            masqueradePodTraffic: ipv6Active && podNetwork.masqueradeIPv6PodTraffic
        )
        let ipv4PodIngressInterface = try resolvePodIngressInterface(
            family: .ipv4,
            podCIDR: canonicalIPv4PodCIDR,
            withdrawFamiliesOnFailure: [.ipv4, .ipv6]
        )
        let ipv6PodIngressInterface: String?
        if ipv6Active, let canonicalIPv6PodCIDR {
            ipv6PodIngressInterface = try resolvePodIngressInterface(
                family: .ipv6,
                podCIDR: canonicalIPv6PodCIDR,
                withdrawFamiliesOnFailure: [.ipv4, .ipv6]
            )
        } else {
            ipv6PodIngressInterface = nil
        }

        try ensurePFEnabled()
        try fileManager.createDirectory(at: anchorsURL, withIntermediateDirectories: true)

        let originalIPv4AnchorData = fileManager.contents(atPath: ipv4AnchorURL.path)
        let originalIPv6AnchorData = fileManager.contents(atPath: ipv6AnchorURL.path)
        let ipv4Anchor = try KubeProxyPFRenderer.renderAnchor(
            ruleSet: ruleSet.selecting(families: [.ipv4]),
            anchorName: config.anchorName,
            localPodCIDR: canonicalIPv4PodCIDR,
            podIngressInterface: ipv4PodIngressInterface,
            masqueradePodTraffic: podNetwork.masqueradeIPv4PodTraffic,
            egressInterface: egressInterface
        )
        let ipv6Anchor: String
        if ipv6Active, let canonicalIPv6PodCIDR, let ipv6PodIngressInterface {
            ipv6Anchor = try KubeProxyPFRenderer.renderAnchor(
                ruleSet: ruleSet.selecting(families: [.ipv6]),
                anchorName: config.ipv6AnchorName,
                localPodCIDR: canonicalIPv6PodCIDR,
                podIngressInterface: ipv6PodIngressInterface,
                masqueradePodTraffic: podNetwork.masqueradeIPv6PodTraffic,
                egressInterface: ipv6Egress?.interfaceName,
                egressSourceAddress: ipv6Egress?.sourceAddress
            )
        } else {
            ipv6Anchor = """
                # generated by container-kube-proxy-macos
                # anchor: \(config.ipv6AnchorName)
                # IPv6 family disabled or not ready

                """
        }

        var candidateConfig = try pfConfigWithAnchorReferences(
            content: originalConfig.content,
            anchorName: config.anchorName,
            anchorURL: ipv4AnchorURL,
            includeNATAnchor: true,
            enabled: true
        )
        candidateConfig = try pfConfigWithAnchorReferences(
            content: candidateConfig,
            anchorName: config.ipv6AnchorName,
            anchorURL: ipv6AnchorURL,
            includeNATAnchor: ipv6Active,
            enabled: ipv6Active
        )
        let rootConfigChanged = candidateConfig != originalConfig.content
        var attemptedRootReload = false
        var attemptedIPv4AnchorReload = false
        var attemptedIPv6AnchorReload = false

        do {
            try ipv4Anchor.write(to: ipv4AnchorURL, atomically: true, encoding: .utf8)
            try ipv6Anchor.write(to: ipv6AnchorURL, atomically: true, encoding: .utf8)
            if rootConfigChanged {
                try validateAndInstallConfig(candidateConfig, configURL: configURL)
                attemptedRootReload = true
                try runPFCTL(arguments: ["-f", configURL.path], failureMessage: "pfctl reload failed")
            } else {
                try runPFCTL(
                    arguments: ["-n", "-a", config.anchorName, "-f", ipv4AnchorURL.path],
                    failureMessage: "pfctl IPv4 anchor validation failed"
                )
                if ipv6Active {
                    try runPFCTL(
                        arguments: ["-n", "-a", config.ipv6AnchorName, "-f", ipv6AnchorURL.path],
                        failureMessage: "pfctl IPv6 anchor validation failed"
                    )
                }
                attemptedIPv4AnchorReload = true
                try runPFCTL(
                    arguments: ["-a", config.anchorName, "-f", ipv4AnchorURL.path],
                    failureMessage: "pfctl IPv4 anchor reload failed"
                )
                if ipv6Active {
                    attemptedIPv6AnchorReload = true
                    try runPFCTL(
                        arguments: ["-a", config.ipv6AnchorName, "-f", ipv6AnchorURL.path],
                        failureMessage: "pfctl IPv6 anchor reload failed"
                    )
                }
            }

            if !ipv6Active {
                attemptedIPv6AnchorReload = true
                try runPFCTL(
                    arguments: ["-a", config.ipv6AnchorName, "-F", "all"],
                    failureMessage: "pfctl IPv6 anchor flush failed"
                )
                if !podNetwork.dualStackEnabled {
                    try fileManager.removeItem(at: ipv6AnchorURL)
                }
            }
        } catch {
            let restoredIPv4Anchor = restoreFile(at: ipv4AnchorURL, originalData: originalIPv4AnchorData)
            let restoredIPv6Anchor = restoreFile(at: ipv6AnchorURL, originalData: originalIPv6AnchorData)
            let restoredConfig = restoreFile(at: configURL, originalData: originalConfig.data)
            var rollbackFailures = fileRestoreFailures(
                restoredFiles: [
                    (restoredIPv4Anchor, ipv4AnchorURL),
                    (restoredIPv6Anchor, ipv6AnchorURL),
                    (restoredConfig, configURL),
                ]
            )
            if attemptedRootReload,
                restoredIPv4Anchor,
                restoredIPv6Anchor,
                restoredConfig,
                originalConfig.data != nil
            {
                if let failure = rollbackFailure({
                    try runPFCTL(arguments: ["-f", configURL.path], failureMessage: "pfctl rollback failed")
                }) {
                    rollbackFailures.append(failure)
                }
            } else if !attemptedRootReload {
                if attemptedIPv4AnchorReload, restoredIPv4Anchor {
                    if originalIPv4AnchorData != nil {
                        if let failure = rollbackFailure({
                            try runPFCTL(
                                arguments: ["-a", config.anchorName, "-f", ipv4AnchorURL.path],
                                failureMessage: "pfctl IPv4 anchor rollback failed"
                            )
                        }) {
                            rollbackFailures.append(failure)
                        }
                    } else {
                        if let failure = rollbackFailure({
                            try runPFCTL(
                                arguments: ["-a", config.anchorName, "-F", "all"],
                                failureMessage: "pfctl IPv4 anchor rollback flush failed"
                            )
                        }) {
                            rollbackFailures.append(failure)
                        }
                    }
                }
                if attemptedIPv6AnchorReload, restoredIPv6Anchor {
                    if originalIPv6AnchorData != nil {
                        if let failure = rollbackFailure({
                            try runPFCTL(
                                arguments: ["-a", config.ipv6AnchorName, "-f", ipv6AnchorURL.path],
                                failureMessage: "pfctl IPv6 anchor rollback failed"
                            )
                        }) {
                            rollbackFailures.append(failure)
                        }
                    } else {
                        if let failure = rollbackFailure({
                            try runPFCTL(
                                arguments: ["-a", config.ipv6AnchorName, "-F", "all"],
                                failureMessage: "pfctl IPv6 anchor rollback flush failed"
                            )
                        }) {
                            rollbackFailures.append(failure)
                        }
                    }
                }
            }
            throw errorIncludingRollbackFailures(error, rollbackFailures: rollbackFailures)
        }
    }

    private func resolvedEgressInterface(masqueradePodTraffic: Bool) throws -> String {
        if let configured = config.configuredEgressInterface {
            return configured
        }
        guard masqueradePodTraffic else {
            // The renderer does not emit an interface-specific rule when NAT is disabled.
            return "lo0"
        }
        return try egressInterfaceResolver.resolveDefaultIPv4EgressInterface()
    }

    private func resolvedIPv6Egress(
        masqueradePodTraffic: Bool
    ) throws -> KubeProxyIPv6Egress? {
        guard masqueradePodTraffic else {
            return nil
        }
        return try ipv6EgressResolver.resolveIPv6Egress(
            configuredInterface: config.configuredIPv6EgressInterface,
            configuredSourceAddress: config.configuredIPv6EgressSourceAddress
        )
    }

    private func resolvePodIngressInterface(
        family: KubeProxyAddressFamily,
        podCIDR: String,
        withdrawFamiliesOnFailure: Set<KubeProxyAddressFamily>
    ) throws -> String {
        do {
            return try podIngressInterfaceResolver.resolvePodIngressInterface(
                family: family,
                podCIDR: podCIDR
            )
        } catch {
            do {
                try withdrawLocked(families: withdrawFamiliesOnFailure)
            } catch let withdrawError {
                throw KubeProxyMacOSError.applyFailed(
                    "Pod ingress interface resolution failed (\(error)); fail-closed PF withdrawal also failed (\(withdrawError))"
                )
            }
            throw error
        }
    }

    private func ensurePFEnabled() throws {
        let output = try runPFCTLReturningStdout(arguments: ["-s", "info"], failureMessage: "pfctl status check failed")
        guard
            output
                .split(separator: "\n")
                .contains(where: { line in
                    line.trimmingCharacters(in: .whitespaces).hasPrefix("Status: Enabled")
                })
        else {
            throw KubeProxyMacOSError.applyFailed("PF is not enabled; enable PF before starting container-kube-proxy-macos")
        }
    }

    private func pfConfigWithAnchorReferences(
        content: String,
        anchorName: String,
        anchorURL: URL,
        includeNATAnchor: Bool,
        enabled: Bool
    ) throws -> String {
        let natAnchor = "nat-anchor \"\(anchorName)\""
        let rdrAnchor = "rdr-anchor \"\(anchorName)\""
        let loadAnchor = "load anchor \"\(anchorName)\" from \"\(anchorURL.path)\""
        var lines = content.components(separatedBy: .newlines)
        if lines.isEmpty {
            lines = [""]
        }

        try validateAnchorReferenceOwnership(
            lines: lines,
            anchorName: anchorName,
            natAnchor: natAnchor,
            rdrAnchor: rdrAnchor,
            loadAnchor: loadAnchor
        )

        let hasNATAnchor = lines.contains { line in
            line.trimmingCharacters(in: .whitespaces) == natAnchor
        }
        if enabled, includeNATAnchor, !hasNATAnchor {
            let insertionIndex =
                lines.firstIndex { line in
                    pfDirective(line, startsWith: "rdr-anchor") || pfDirective(line, startsWith: "nat-anchor")
                } ?? max(lines.endIndex - 1, lines.startIndex)
            lines.insert(natAnchor, at: insertionIndex)
        } else if !enabled || !includeNATAnchor {
            lines.removeAll { line in
                line.trimmingCharacters(in: .whitespaces) == natAnchor
            }
        }

        if enabled, !lines.contains(where: { normalizedPFDirective($0) == rdrAnchor }) {
            let anchorKeywords = ["scrub-anchor", "nat-anchor", "rdr-anchor", "dummynet-anchor", "anchor", "load anchor"]
            let insertionIndex =
                lines.firstIndex { line in
                    anchorKeywords.drop(while: { $0 != "rdr-anchor" }).contains { keyword in
                        pfDirective(line, startsWith: keyword)
                    }
                } ?? max(lines.endIndex - 1, lines.startIndex)
            lines.insert(rdrAnchor, at: insertionIndex)
        } else if !enabled {
            lines.removeAll { normalizedPFDirective($0) == rdrAnchor }
        }

        if enabled, !lines.contains(where: { normalizedPFDirective($0) == loadAnchor }) {
            lines.insert(loadAnchor, at: max(lines.endIndex - 1, lines.startIndex))
        } else if !enabled {
            lines.removeAll { normalizedPFDirective($0) == loadAnchor }
        }

        return lines.joined(separator: "\n")
    }

    private func validateAnchorReferenceOwnership(
        lines: [String],
        anchorName: String,
        natAnchor: String,
        rdrAnchor: String,
        loadAnchor: String
    ) throws {
        let matchingNAT = lines.filter {
            directive($0, matchesAnchorReference: natAnchor)
        }
        let matchingRDR = lines.filter {
            directive($0, matchesAnchorReference: rdrAnchor)
        }
        let loadPrefix = "load anchor \"\(anchorName)\""
        let matchingLoad = lines.filter {
            directive($0, matchesAnchorReference: loadPrefix)
        }
        guard !matchingNAT.isEmpty || !matchingRDR.isEmpty || !matchingLoad.isEmpty else {
            return
        }

        let hasUniqueManagedReferences =
            matchingNAT.count <= 1
            && matchingRDR.count == 1
            && matchingLoad.count == 1
            && matchingNAT.allSatisfy { normalizedPFDirective($0) == natAnchor }
            && normalizedPFDirective(matchingRDR[0]) == rdrAnchor
            && normalizedPFDirective(matchingLoad[0]) == loadAnchor
        guard hasUniqueManagedReferences else {
            throw KubeProxyMacOSError.applyFailed(
                "PF config contains conflicting or incomplete references for anchor \(anchorName); expected one rdr-anchor, at most one nat-anchor, and one load anchor from the managed path"
            )
        }
    }

    private func directive(_ line: String, matchesAnchorReference reference: String) -> Bool {
        let normalized = normalizedPFDirective(line)
        return normalized == reference
            || normalized.hasPrefix("\(reference) ")
            || normalized.hasPrefix("\(reference)\t")
    }

    private func anchorURL(named anchorName: String) -> URL {
        URL(fileURLWithPath: config.anchorsPath).appendingPathComponent(anchorName)
    }

    private func readPFConfig() throws -> (data: Data?, content: String) {
        let data = FileManager.default.contents(atPath: config.configPath)
        let content =
            try data.map { data in
                guard let value = String(data: data, encoding: .utf8) else {
                    throw KubeProxyMacOSError.applyFailed("\(config.configPath) is not valid UTF-8")
                }
                return value
            } ?? ""
        return (data, content)
    }

    private func hasAnchorReferences(content: String, anchorName: String) -> Bool {
        let directives = [
            "nat-anchor \"\(anchorName)\"",
            "rdr-anchor \"\(anchorName)\"",
            "load anchor \"\(anchorName)\"",
        ]
        return content.components(separatedBy: .newlines).contains { line in
            let normalized = normalizedPFDirective(line)
            return directives.contains { directive in
                normalized == directive || normalized.hasPrefix("\(directive) ")
            }
        }
    }

    private func withMutationLock<T>(_ operation: () throws -> T) throws -> T {
        Self.processApplyLock.lock()
        defer { Self.processApplyLock.unlock() }

        let descriptor = advisoryLockPath.withCString { path in
            Darwin.open(path, O_CREAT | O_RDWR, S_IRUSR | S_IWUSR)
        }
        guard descriptor >= 0 else {
            throw KubeProxyMacOSError.applyFailed(
                "failed to open PF advisory lock at \(advisoryLockPath): \(posixErrorDescription())"
            )
        }
        defer { Darwin.close(descriptor) }
        _ = Darwin.fcntl(descriptor, F_SETFD, FD_CLOEXEC)

        var lock = Darwin.flock()
        lock.l_type = Int16(F_WRLCK)
        lock.l_whence = Int16(SEEK_SET)
        while Darwin.fcntl(descriptor, F_SETLKW, &lock) != 0 {
            guard errno == EINTR else {
                throw KubeProxyMacOSError.applyFailed(
                    "failed to acquire PF advisory lock at \(advisoryLockPath): \(posixErrorDescription())"
                )
            }
        }
        defer {
            var unlock = Darwin.flock()
            unlock.l_type = Int16(F_UNLCK)
            unlock.l_whence = Int16(SEEK_SET)
            _ = Darwin.fcntl(descriptor, F_SETLK, &unlock)
        }
        return try operation()
    }

    private func posixErrorDescription() -> String {
        kubeProxyString(decodingCString: strerror(errno))
    }

    private func validateAndInstallConfig(_ content: String, configURL: URL) throws {
        let temporaryURL =
            configURL
            .deletingLastPathComponent()
            .appendingPathComponent(".\(configURL.lastPathComponent).container-kube-proxy.\(UUID().uuidString).tmp")
        try content.write(to: temporaryURL, atomically: true, encoding: .utf8)
        defer {
            try? FileManager.default.removeItem(at: temporaryURL)
        }

        try runPFCTL(arguments: ["-n", "-f", temporaryURL.path], failureMessage: "pfctl validation failed")
        try content.write(to: configURL, atomically: true, encoding: .utf8)
    }

    private func normalizedPFDirective(_ line: String) -> String {
        line.trimmingCharacters(in: .whitespaces)
    }

    private func pfDirective(_ line: String, startsWith keyword: String) -> Bool {
        let directive = normalizedPFDirective(line)
        return directive.hasPrefix("\(keyword) ") || directive.hasPrefix("\(keyword)\t")
    }

    private func fileRestoreFailures(restoredFiles: [(Bool, URL)]) -> [String] {
        restoredFiles.compactMap { restored, url in
            restored ? nil : "failed to restore \(url.path)"
        }
    }

    private func rollbackFailure(_ operation: () throws -> Void) -> String? {
        do {
            try operation()
            return nil
        } catch {
            return String(describing: error)
        }
    }

    private func errorIncludingRollbackFailures(
        _ primaryError: any Error,
        rollbackFailures: [String]
    ) -> any Error {
        guard !rollbackFailures.isEmpty else {
            return primaryError
        }
        return KubeProxyMacOSError.applyFailed(
            "PF update failed: \(primaryError); rollback was incomplete: \(rollbackFailures.joined(separator: "; "))"
        )
    }

    @discardableResult
    private func restoreFile(at url: URL, originalData: Data?) -> Bool {
        do {
            if let originalData {
                try originalData.write(to: url, options: .atomic)
            } else if FileManager.default.fileExists(atPath: url.path) {
                try FileManager.default.removeItem(at: url)
            }
            return true
        } catch {
            return false
        }
    }

    private func removeFileIfPresent(at url: URL) throws {
        guard FileManager.default.fileExists(atPath: url.path) else {
            return
        }
        try FileManager.default.removeItem(at: url)
    }

    private func flushManagedAnchors(_ families: Set<KubeProxyAddressFamily>) throws {
        if families.contains(.ipv4) {
            try runPFCTL(
                arguments: ["-a", config.anchorName, "-F", "all"],
                failureMessage: "pfctl IPv4 anchor flush failed"
            )
        }
        if families.contains(.ipv6) {
            try runPFCTL(
                arguments: ["-a", config.ipv6AnchorName, "-F", "all"],
                failureMessage: "pfctl IPv6 anchor flush failed"
            )
        }
    }

    private func runPFCTL(arguments: [String], failureMessage: String) throws {
        let process = Process()
        let output = Pipe()
        process.executableURL = URL(fileURLWithPath: config.pfctlPath)
        process.arguments = arguments
        process.standardOutput = output
        process.standardError = output

        do {
            try process.run()
        } catch {
            throw KubeProxyMacOSError.applyFailed("\(failureMessage): \(error)")
        }

        // Drain while pfctl is running. Waiting before reading can deadlock if
        // either output stream fills its pipe while the PF mutation lock is held.
        let outputData = output.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            let detail =
                String(data: outputData, encoding: .utf8)?
                .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            throw KubeProxyMacOSError.applyFailed(
                "\(failureMessage) with status \(process.terminationStatus): \(detail)"
            )
        }
    }

    private func runPFCTLReturningStdout(arguments: [String], failureMessage: String) throws -> String {
        let process = Process()
        let output = Pipe()
        process.executableURL = URL(fileURLWithPath: config.pfctlPath)
        process.arguments = arguments
        process.standardOutput = output
        process.standardError = output

        do {
            try process.run()
        } catch {
            throw KubeProxyMacOSError.applyFailed("\(failureMessage): \(error)")
        }

        // Use one continuously drained pipe for both streams so neither can
        // block pfctl while the caller owns the PF mutation lock.
        let outputData = output.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            let detail =
                String(data: outputData, encoding: .utf8)?
                .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            throw KubeProxyMacOSError.applyFailed(
                "\(failureMessage) with status \(process.terminationStatus): \(detail)"
            )
        }
        return String(data: outputData, encoding: .utf8) ?? ""
    }
}

public struct KubeProxyDryRunRuleApplier: KubeProxyRuleApplying {
    public let output: @Sendable (String) -> Void
    public let anchorName: String
    public let egressInterface: String?
    public let ipv6EgressInterface: String?
    public let ipv6EgressSourceAddress: String?
    private let egressInterfaceResolver: any KubeProxyEgressInterfaceResolving
    private let ipv6EgressResolver: any KubeProxyIPv6EgressResolving
    private let podIngressInterfaceResolver: any KubeProxyPodIngressInterfaceResolving

    public init(
        anchorName: String = "com.apple.container.kube-proxy",
        egressInterface: String? = nil,
        ipv6EgressInterface: String? = nil,
        ipv6EgressSourceAddress: String? = nil,
        egressInterfaceResolver: any KubeProxyEgressInterfaceResolving = KubeProxyDefaultIPv4EgressInterfaceResolver(),
        ipv6EgressResolver: any KubeProxyIPv6EgressResolving = KubeProxyDefaultIPv6EgressResolver(),
        podIngressInterfaceResolver: any KubeProxyPodIngressInterfaceResolving = KubeProxyDefaultPodIngressInterfaceResolver(),
        output: @escaping @Sendable (String) -> Void
    ) {
        self.anchorName = anchorName
        self.egressInterface = egressInterface
        self.ipv6EgressInterface = ipv6EgressInterface
        self.ipv6EgressSourceAddress = ipv6EgressSourceAddress
        self.egressInterfaceResolver = egressInterfaceResolver
        self.ipv6EgressResolver = ipv6EgressResolver
        self.podIngressInterfaceResolver = podIngressInterfaceResolver
        self.output = output
    }

    public func apply(
        _ ruleSet: KubeProxyRuleSet,
        localPodCIDR: String,
        masqueradePodTraffic: Bool = false
    ) throws {
        guard let canonicalPodCIDR = KubeProxyIPv4CIDR.canonicalize(localPodCIDR),
            canonicalPodCIDR == localPodCIDR
        else {
            throw KubeProxyMacOSError.applyFailed("local PodCIDR is not canonical IPv4 CIDR")
        }
        let resolvedEgressInterface: String
        if let egressInterface {
            resolvedEgressInterface = egressInterface
        } else if masqueradePodTraffic {
            resolvedEgressInterface = try egressInterfaceResolver.resolveDefaultIPv4EgressInterface()
        } else {
            resolvedEgressInterface = "lo0"
        }
        let podIngressInterface = try podIngressInterfaceResolver.resolvePodIngressInterface(
            family: .ipv4,
            podCIDR: canonicalPodCIDR
        )
        output(
            try KubeProxyPFRenderer.renderAnchor(
                ruleSet: ruleSet.selecting(families: [.ipv4]),
                anchorName: anchorName,
                localPodCIDR: canonicalPodCIDR,
                podIngressInterface: podIngressInterface,
                masqueradePodTraffic: masqueradePodTraffic,
                egressInterface: resolvedEgressInterface
            ))
    }

    public func apply(
        _ ruleSet: KubeProxyRuleSet,
        podNetwork: KubeProxyFamilyRuleApplication
    ) throws {
        guard podNetwork.ipv4Ready else {
            throw KubeProxyMacOSError.applyFailed("pod network IPv4 family is not ready")
        }
        try apply(
            ruleSet.selecting(families: [.ipv4]),
            localPodCIDR: podNetwork.ipv4PodCIDR,
            masqueradePodTraffic: podNetwork.masqueradeIPv4PodTraffic
        )

        let ipv6AnchorName = "\(anchorName).ipv6"
        if podNetwork.dualStackEnabled, podNetwork.ipv6Ready {
            guard let ipv6PodCIDR = podNetwork.ipv6PodCIDR,
                KubeProxyIPv6CIDR.canonicalize(ipv6PodCIDR) == ipv6PodCIDR
            else {
                throw KubeProxyMacOSError.applyFailed(
                    "ready IPv6 family requires a canonical local IPv6 PodCIDR"
                )
            }
            let podIngressInterface = try podIngressInterfaceResolver.resolvePodIngressInterface(
                family: .ipv6,
                podCIDR: ipv6PodCIDR
            )
            let ipv6Egress =
                try podNetwork.masqueradeIPv6PodTraffic
                ? ipv6EgressResolver.resolveIPv6Egress(
                    configuredInterface: ipv6EgressInterface,
                    configuredSourceAddress: ipv6EgressSourceAddress
                )
                : nil
            output(
                try KubeProxyPFRenderer.renderAnchor(
                    ruleSet: ruleSet.selecting(families: [.ipv6]),
                    anchorName: ipv6AnchorName,
                    localPodCIDR: ipv6PodCIDR,
                    podIngressInterface: podIngressInterface,
                    masqueradePodTraffic: podNetwork.masqueradeIPv6PodTraffic,
                    egressInterface: ipv6Egress?.interfaceName,
                    egressSourceAddress: ipv6Egress?.sourceAddress
                ))
        } else if podNetwork.dualStackEnabled {
            output("# pfctl -a \(ipv6AnchorName) -F all\n")
        }
    }

    public func withdraw() throws {
        output("# pfctl -a \(anchorName) -F all\n")
        output("# pfctl -a \(anchorName).ipv6 -F all\n")
    }

    public func withdrawIPv6() throws {
        output("# pfctl -a \(anchorName).ipv6 -F all\n")
    }
}
