//===----------------------------------------------------------------------===//
// Copyright © 2026 Apple Inc. and the container project authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

import Foundation

public enum KubeProxyPFRenderer {
    public static func renderAnchor(ruleSet: KubeProxyRuleSet, anchorName: String = "com.apple.container.kube-proxy") -> String {
        var lines: [String] = [
            "# generated by container-kube-proxy-macos",
            "# anchor: \(anchorName)",
            "# generation: \(ruleSet.generation)",
            "",
        ]

        for rule in ruleSet.rules {
            let tableName = tableName(for: rule)
            let addresses = rule.backends.map(\.ip).sorted().joined(separator: ", ")
            lines.append("table <\(tableName)> persist { \(addresses) }")
        }

        if !ruleSet.rules.isEmpty {
            lines.append("")
        }

        for rule in ruleSet.rules {
            let tableName = tableName(for: rule)
            let backendPort = rule.backends[0].port
            let roundRobin = rule.backends.count > 1 ? " round-robin" : ""
            lines.append(
                "rdr pass inet proto \(rule.protocolName.pfName) from any to \(rule.clusterIP) port \(rule.servicePort) -> <\(tableName)> port \(backendPort)\(roundRobin)"
            )
        }

        if !ruleSet.issues.isEmpty {
            lines.append("")
            for issue in ruleSet.issues {
                lines.append("# issue \(issue.id): \(issue.message)")
            }
        }

        lines.append("")
        return lines.joined(separator: "\n")
    }

    public static func tableName(for rule: KubeProxyServiceRule) -> String {
        let raw = [
            "ckp",
            rule.namespace,
            rule.serviceName,
            rule.portName ?? "\(rule.servicePort)",
            rule.protocolName.rawValue.lowercased(),
            "\(rule.servicePort)",
        ].joined(separator: "_")

        let sanitized = raw.map { character -> Character in
            character.isLetter || character.isNumber ? character : "_"
        }
        return String(sanitized)
    }
}

public protocol KubeProxyRuleApplying: Sendable {
    func apply(_ ruleSet: KubeProxyRuleSet) throws
}

public struct KubeProxyPFRuleApplier: KubeProxyRuleApplying {
    public let config: KubeProxyPFConfig

    public init(config: KubeProxyPFConfig = KubeProxyPFConfig()) {
        self.config = config
    }

    public func apply(_ ruleSet: KubeProxyRuleSet) throws {
        let fileManager = FileManager.default
        let configURL = URL(fileURLWithPath: config.configPath)
        let anchorsURL = URL(fileURLWithPath: config.anchorsPath)
        let anchorURL = anchorsURL.appendingPathComponent(config.anchorName)

        try ensurePFEnabled()
        try fileManager.createDirectory(at: anchorsURL, withIntermediateDirectories: true)

        let originalConfigData = fileManager.contents(atPath: configURL.path)
        let originalConfig =
            try originalConfigData.map { data in
                guard let value = String(data: data, encoding: .utf8) else {
                    throw KubeProxyMacOSError.applyFailed("\(config.configPath) is not valid UTF-8")
                }
                return value
            } ?? ""
        let originalAnchorData = fileManager.contents(atPath: anchorURL.path)
        let anchor = KubeProxyPFRenderer.renderAnchor(ruleSet: ruleSet, anchorName: config.anchorName)
        let candidateConfig = pfConfigWithAnchorReferences(content: originalConfig, anchorURL: anchorURL)

        do {
            try anchor.write(to: anchorURL, atomically: true, encoding: .utf8)
            if candidateConfig != originalConfig {
                try validateAndInstallConfig(candidateConfig, configURL: configURL)
            } else {
                try runPFCTL(arguments: ["-n", "-f", configURL.path], failureMessage: "pfctl validation failed")
            }
            try runPFCTL(arguments: ["-f", configURL.path], failureMessage: "pfctl reload failed")
        } catch {
            restoreFile(at: anchorURL, originalData: originalAnchorData)
            restoreFile(at: configURL, originalData: originalConfigData)
            throw error
        }
    }

    private func ensurePFEnabled() throws {
        let output = try runPFCTLReturningStdout(arguments: ["-s", "info"], failureMessage: "pfctl status check failed")
        guard
            output
                .split(separator: "\n")
                .contains(where: { line in
                    line.trimmingCharacters(in: .whitespaces).hasPrefix("Status: Enabled")
                })
        else {
            throw KubeProxyMacOSError.applyFailed("PF is not enabled; enable PF before starting container-kube-proxy-macos")
        }
    }

    private func pfConfigWithAnchorReferences(content: String, anchorURL: URL) -> String {
        let rdrAnchor = "rdr-anchor \"\(config.anchorName)\""
        let loadAnchor = "load anchor \"\(config.anchorName)\" from \"\(anchorURL.path)\""
        var lines = content.components(separatedBy: .newlines)
        if lines.isEmpty {
            lines = [""]
        }

        if !content.contains(rdrAnchor) {
            let anchorKeywords = ["scrub-anchor", "nat-anchor", "rdr-anchor", "dummynet-anchor", "anchor", "load anchor"]
            let insertionIndex =
                lines.firstIndex { line in
                    anchorKeywords.drop(while: { $0 != "rdr-anchor" }).contains { keyword in
                        line.starts(with: keyword)
                    }
                } ?? max(lines.endIndex - 1, lines.startIndex)
            lines.insert(rdrAnchor, at: insertionIndex)
        }

        if !content.contains(loadAnchor) {
            lines.insert(loadAnchor, at: max(lines.endIndex - 1, lines.startIndex))
        }

        return lines.joined(separator: "\n")
    }

    private func validateAndInstallConfig(_ content: String, configURL: URL) throws {
        let temporaryURL =
            configURL
            .deletingLastPathComponent()
            .appendingPathComponent(".\(configURL.lastPathComponent).container-kube-proxy.\(UUID().uuidString).tmp")
        try content.write(to: temporaryURL, atomically: true, encoding: .utf8)
        defer {
            try? FileManager.default.removeItem(at: temporaryURL)
        }

        try runPFCTL(arguments: ["-n", "-f", temporaryURL.path], failureMessage: "pfctl validation failed")
        try content.write(to: configURL, atomically: true, encoding: .utf8)
    }

    private func restoreFile(at url: URL, originalData: Data?) {
        if let originalData {
            try? originalData.write(to: url, options: .atomic)
        } else {
            try? FileManager.default.removeItem(at: url)
        }
    }

    private func runPFCTL(arguments: [String], failureMessage: String) throws {
        let process = Process()
        let stderr = Pipe()
        process.executableURL = URL(fileURLWithPath: config.pfctlPath)
        process.arguments = arguments
        process.standardOutput = FileHandle.nullDevice
        process.standardError = stderr

        do {
            try process.run()
        } catch {
            throw KubeProxyMacOSError.applyFailed("\(failureMessage): \(error)")
        }

        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            let data = stderr.fileHandleForReading.readDataToEndOfFile()
            let output = String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            throw KubeProxyMacOSError.applyFailed("\(failureMessage) with status \(process.terminationStatus): \(output)")
        }
    }

    private func runPFCTLReturningStdout(arguments: [String], failureMessage: String) throws -> String {
        let process = Process()
        let stdout = Pipe()
        let stderr = Pipe()
        process.executableURL = URL(fileURLWithPath: config.pfctlPath)
        process.arguments = arguments
        process.standardOutput = stdout
        process.standardError = stderr

        do {
            try process.run()
        } catch {
            throw KubeProxyMacOSError.applyFailed("\(failureMessage): \(error)")
        }

        process.waitUntilExit()
        let outputData = stdout.fileHandleForReading.readDataToEndOfFile()
        guard process.terminationStatus == 0 else {
            let errorData = stderr.fileHandleForReading.readDataToEndOfFile()
            let output = String(data: errorData, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            throw KubeProxyMacOSError.applyFailed("\(failureMessage) with status \(process.terminationStatus): \(output)")
        }
        return String(data: outputData, encoding: .utf8) ?? ""
    }
}

public struct KubeProxyDryRunRuleApplier: KubeProxyRuleApplying {
    public let output: @Sendable (String) -> Void
    public let anchorName: String

    public init(anchorName: String = "com.apple.container.kube-proxy", output: @escaping @Sendable (String) -> Void) {
        self.anchorName = anchorName
        self.output = output
    }

    public func apply(_ ruleSet: KubeProxyRuleSet) throws {
        output(KubeProxyPFRenderer.renderAnchor(ruleSet: ruleSet, anchorName: anchorName))
    }
}
