apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: "127.0.0.1"
port: 10250
readOnlyPort: 0
staticPodPath: "/etc/kubernetes/manifests"
containerRuntimeEndpoint: "unix:///var/run/container-cri-macos.sock"
imageServiceEndpoint: "unix:///var/run/container-cri-macos.sock"
syncFrequency: "5s"
fileCheckFrequency: "5s"
runtimeRequestTimeout: "2m"
failSwapOn: false
cgroupsPerQOS: false
enforceNodeAllocatable: []
eventRecordQPS: 5
enableServer: true
localStorageCapacityIsolation: false
makeIPTablesUtilChains: false
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
authorization:
  mode: Webhook
